### ISSUE TITLE
Login database empty after save server.R

### ISSUE THREAD

**Issue by ragapack** [AbubakerSuliman/Shiny-login-page#1]
First of all, Great Work, it´s very close what I am looking for.
I am making some Tests and translating strings to Portuguese and after save the server.R file former created accounts are deleted. I can create it again with same Username and Password, and I can reload the page on R Studio and on Shiny Server too, the credentials stay, but if I change something at the server.R and save the file the credentials are gone.
Where are the credentials stored? The line 
dbExecute(pool, 'CREATE TABLE user (user_name TEXT, country TEXT, email TEXT, password TEXT)')
overwrite the existing table?

**Comment by AbubakerSuliman** [comment]
@ragapack thanks for the kind words and sorry for the late reply.
From `?RSQLite::SQLite()` 
When _dbname_ is "" will create a temporary on-disk database. The file will be deleted when the connection is closed. 
Therefore, credentials are gone every time you save and run (i.e. reload) or close and open the server.R, as the App will start with a fresh DB each time.
 
Now I think commits https://github.com/AbubakerSuliman/Shiny-login-page/commit/f639fcf25a093fa3bb04ce0f2325a459cc652bba and https://github.com/AbubakerSuliman/Shiny-login-page/commit/6248f2b7f73251f656b7dd506bacc94d5bcd8039 solved this issue.
